apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: smokey-client
  name: smokey-client
spec:
  replicas: 3
  selector:
    matchLabels:
      run: smokey-client
  template:
    metadata:
      labels:
        run: smokey-client
    spec:
      containers:
      - image: gcr.io/mythic-maxim-255321/smokey-client:BUILD
        name: smokey-client
        env:
        - name: SERVER
          value: "http://smokey-service:8082"

