apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: smokey-client
  name: smokey-client
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: smokey-client
  type: LoadBalancer
status:
  loadBalancer: {}
